name: angomovie_iptv
description: AngoMovie IPTV - Tv ao Vivo gratuitamente 
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Universal Video Player Engine (Decodifica áudio Dolby AC-3, E-AC-3, DTS e vídeos .ts)
  flutter_vlc_player: ^7.4.1

  # HTTP & Networking
  http: ^1.2.0

  # Local Storage (Rápido e Cacheado)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State Management (Reatividade na UI)
  provider: ^6.1.2

  # Image Loading (Cache inteligente de logotipos em RAM/Disco)
  cached_network_image: ^3.4.1

  # Shared Preferences (Definições de Usuário e Segurança)
  shared_preferences: ^2.3.2

  # Android Intents (Para abrir canais no VLC ou MX Player externo)
  android_intent_plus: ^5.0.2

  # Connectivity (Monitoramento de estado da rede)
  connectivity_plus: ^6.1.4

  # Wakelock (Impede que a TV ou Telemóvel desligue o ecrã durante a reprodução)
  wakelock_plus: ^1.2.8

  # Path Provider (Para logs físicos de depuração e caminhos de arquivo)
  path_provider: ^2.1.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
