name: Build AngoMovie APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Caching do Gradle para acelerar as compilações futuras no GitHub
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Ativa o cache nativo do SDK do Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Hive Adapters
        run: dart run build_runner build --delete-conflicting-outputs

      # COMPILAÇÃO INTELIGENTE: Divide o APK por arquiteturas, reduzindo o tamanho em até 70%!
      - name: Build APK
        run: |
          flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols

      # Upload dos arquivos divididos (Muito menores e otimizados)
      - name: Upload APKs Otimizados
        uses: actions/upload-artifact@v4
        with:
          name: AngoMovie-Release-APKs
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
